// Type declaration for Prisma client with custom output path
// This allows TypeScript to recognize imports from '../../node_modules/.prisma/client'
// The actual PrismaClient is generated by Prisma, this just tells TypeScript the module exists

declare module '../../node_modules/.prisma/client' {
  // PrismaClient is actually a class exported from the generated index file
  // We use 'any' here and let the actual generated files provide the types
  export class PrismaClient {
    constructor(options?: any);
    $connect(): Promise<void>;
    $disconnect(): Promise<void>;
    [key: string]: any;
  }
  
  // Export all other types that Prisma generates
  // TypeScript will use the actual generated .d.ts files for proper types
  export * from '../../node_modules/.prisma/client/index';
}
